/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as StudentVisaRouteImport } from './routes/student-visa'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PlanDreamTripRouteImport } from './routes/plan-dream-trip'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MalaysiaStudentVisaRouteImport } from './routes/malaysia-student-visa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as HajjUmrahRouteImport } from './routes/hajj-umrah'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as ApiFlightsRouteImport } from './routes/api.flights'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentVisaRoute = StudentVisaRouteImport.update({
  id: '/student-visa',
  path: '/student-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDreamTripRoute = PlanDreamTripRouteImport.update({
  id: '/plan-dream-trip',
  path: '/plan-dream-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MalaysiaStudentVisaRoute = MalaysiaStudentVisaRouteImport.update({
  id: '/malaysia-student-visa',
  path: '/malaysia-student-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjUmrahRoute = HajjUmrahRouteImport.update({
  id: '/hajj-umrah',
  path: '/hajj-umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const ApiFlightsRoute = ApiFlightsRouteImport.update({
  id: '/api/flights',
  path: '/api/flights',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/flights': typeof FlightsRoute
  '/hajj-umrah': typeof HajjUmrahRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/malaysia-student-visa': typeof MalaysiaStudentVisaRoute
  '/packages': typeof PackagesRouteWithChildren
  '/plan-dream-trip': typeof PlanDreamTripRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-visa': typeof StudentVisaRoute
  '/testimonials': typeof TestimonialsRoute
  '/visa': typeof VisaRoute
  '/api/flights': typeof ApiFlightsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/flights': typeof FlightsRoute
  '/hajj-umrah': typeof HajjUmrahRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/malaysia-student-visa': typeof MalaysiaStudentVisaRoute
  '/packages': typeof PackagesRouteWithChildren
  '/plan-dream-trip': typeof PlanDreamTripRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-visa': typeof StudentVisaRoute
  '/testimonials': typeof TestimonialsRoute
  '/visa': typeof VisaRoute
  '/api/flights': typeof ApiFlightsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/flights': typeof FlightsRoute
  '/hajj-umrah': typeof HajjUmrahRoute
  '/hotels': typeof HotelsRoute
  '/login': typeof LoginRoute
  '/malaysia-student-visa': typeof MalaysiaStudentVisaRoute
  '/packages': typeof PackagesRouteWithChildren
  '/plan-dream-trip': typeof PlanDreamTripRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-visa': typeof StudentVisaRoute
  '/testimonials': typeof TestimonialsRoute
  '/visa': typeof VisaRoute
  '/api/flights': typeof ApiFlightsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/book'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/flights'
    | '/hajj-umrah'
    | '/hotels'
    | '/login'
    | '/malaysia-student-visa'
    | '/packages'
    | '/plan-dream-trip'
    | '/signup'
    | '/sitemap.xml'
    | '/student-visa'
    | '/testimonials'
    | '/visa'
    | '/api/flights'
    | '/destinations/$slug'
    | '/packages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/book'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/flights'
    | '/hajj-umrah'
    | '/hotels'
    | '/login'
    | '/malaysia-student-visa'
    | '/packages'
    | '/plan-dream-trip'
    | '/signup'
    | '/sitemap.xml'
    | '/student-visa'
    | '/testimonials'
    | '/visa'
    | '/api/flights'
    | '/destinations/$slug'
    | '/packages/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/book'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/flights'
    | '/hajj-umrah'
    | '/hotels'
    | '/login'
    | '/malaysia-student-visa'
    | '/packages'
    | '/plan-dream-trip'
    | '/signup'
    | '/sitemap.xml'
    | '/student-visa'
    | '/testimonials'
    | '/visa'
    | '/api/flights'
    | '/destinations/$slug'
    | '/packages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  FlightsRoute: typeof FlightsRoute
  HajjUmrahRoute: typeof HajjUmrahRoute
  HotelsRoute: typeof HotelsRoute
  LoginRoute: typeof LoginRoute
  MalaysiaStudentVisaRoute: typeof MalaysiaStudentVisaRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PlanDreamTripRoute: typeof PlanDreamTripRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentVisaRoute: typeof StudentVisaRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VisaRoute: typeof VisaRoute
  ApiFlightsRoute: typeof ApiFlightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-visa': {
      id: '/student-visa'
      path: '/student-visa'
      fullPath: '/student-visa'
      preLoaderRoute: typeof StudentVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-dream-trip': {
      id: '/plan-dream-trip'
      path: '/plan-dream-trip'
      fullPath: '/plan-dream-trip'
      preLoaderRoute: typeof PlanDreamTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malaysia-student-visa': {
      id: '/malaysia-student-visa'
      path: '/malaysia-student-visa'
      fullPath: '/malaysia-student-visa'
      preLoaderRoute: typeof MalaysiaStudentVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj-umrah': {
      id: '/hajj-umrah'
      path: '/hajj-umrah'
      fullPath: '/hajj-umrah'
      preLoaderRoute: typeof HajjUmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/api/flights': {
      id: '/api/flights'
      path: '/api/flights'
      fullPath: '/api/flights'
      preLoaderRoute: typeof ApiFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  FlightsRoute: FlightsRoute,
  HajjUmrahRoute: HajjUmrahRoute,
  HotelsRoute: HotelsRoute,
  LoginRoute: LoginRoute,
  MalaysiaStudentVisaRoute: MalaysiaStudentVisaRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PlanDreamTripRoute: PlanDreamTripRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentVisaRoute: StudentVisaRoute,
  TestimonialsRoute: TestimonialsRoute,
  VisaRoute: VisaRoute,
  ApiFlightsRoute: ApiFlightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
